"""What has to match before rendered audio can be reused.

A byte-for-byte mirror of `bookbinder/fingerprint.py`. The two environments
cannot import each other, and both sides need this: narrator writes the
fingerprints, bookbinder checks them before it will assemble a book.

Do not edit this file alone. `apps/bookbinder/tests/test_fingerprint.py` loads
both copies and compares their output on the same inputs, so a change made
here and not there fails the suite rather than quietly splitting the two into
different notions of "unchanged".
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

# Bumped when a change to the rendering path makes previously rendered audio
# not worth keeping, even though nothing about the request changed. Rare, and
# expensive: it invalidates every fragment of every book.
RENDERER_VERSION = 1

# Long enough that a collision is not a practical concern, short enough to
# read in a manifest and compare by eye.
DIGEST_CHARS = 32


def _digest(payload: dict) -> str:
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False,
                         separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()[:DIGEST_CHARS]


def voice_revision(root: Path, voice: str) -> str:
    """Identity of the voice as it currently stands on disk.

    Covers the profile, which names the reference clips and the checkpoint,
    and the derived latents, which change when a voice is re-cloned from new
    material. Re-cloning a voice must invalidate audio made with the old one;
    nothing else in the request would show that it had happened.
    """
    digest = hashlib.sha256()
    for path in (root / "data" / "voices" / f"{voice}.json",
                 root / "data" / "voices" / voice / "latents.pt"):
        if path.is_file():
            digest.update(path.name.encode("utf-8"))
            digest.update(path.read_bytes())
    return digest.hexdigest()[:DIGEST_CHARS]


def fragment_fingerprint(
    *,
    text: str,
    language: str,
    model: str,
    voice: str,
    voice_revision: str,
    settings: dict,
    renderer_version: int = RENDERER_VERSION,
) -> str:
    """The identity of one rendered fragment.

    `model` is the registry identity including its revision where one is
    pinned, so the same model at two checkpoints is not the same model.
    `settings` is the effective set the backend actually implements: a control
    it ignores cannot have changed the audio, so it must not invalidate it
    either.
    """
    return _digest({
        "text": text,
        "language": language,
        "model": model,
        "voice": voice,
        "voice_revision": voice_revision,
        # Floats so that 1 and 1.0 are one value rather than two.
        "settings": {k: float(v) for k, v in sorted(settings.items())},
        "renderer": renderer_version,
    })
